### ISSUE TITLE
No-code contributions

### ISSUE THREAD

**Issue by bacloud23** [bacloud23/classified-ads#36]
Classified-ads is composed not only of code! So any contribution of these forms is welcome as well 

- Enrich multilingual content: 
        - Providing a whole new language of the UI is `hacktoberfest-accepted` [back](https://github.com/bacloud23/classified-ads/tree/main/data/locales) & [front](https://github.com/bacloud22/classified-ads/tree/main/public/locales) 
        - Verifying a whole existing language is `hacktoberfest-accepted` but only once for each existing language. For revision of a translation, please take the English language as the base correct language which is the only one I'm 100% sure about.
     
- A whole audit (well a revision let's say) of the UI with SEO and UX enhancement list
- Sketches: Some sketches to illustrate different sections: Donations, Skills, Meetings, Blogs, Hobbies.

**Comment by danieled-it** [comment]
hey @bacloud23 , I think I could help with some Italian translations, I just need a bit of help on how to spin this up locally to try, I've never dealt with web-apps and I think it'll be better if I try to translate from English only after seeing those words in context, don't wanna risk to look like a bot with my results 😄

**Comment by bacloud23** [comment]
Hey @danieled-it, 
Thank you so much ! This is great to have Italian as an addition.

This is a deployment of one earlier version (you can see the map is broke and so on) but everything is the same in regards of English: https://iciannonces.fr/

**Comment by bacloud23** [comment]
Actually I guess Installation is easy, but I 'll be happy to know what are the problems you encountered following README?

**Comment by danieled-it** [comment]
I mean, if I've never handled a single web-app in my life, seeing a prerequisite like:

> Prepare database
> 
>     Redis database must be up
>     MongoDB must be up with the following dbs and collections
>     DBs: {listings_db} & Collections: {listing, words, comment, users, userstemp, visitors-default-current, visitors-default}

or even dealing with `npm` scares me out from even trying, I don't want to mess up my WSL if I don't know what I'm doing with it :)

**Comment by bacloud23** [comment]
Just noting that I corrected the link to [back](https://github.com/bacloud23/classified-ads/tree/main/data/locales) translations.

**Comment by marinoffDev** [comment]
Hey @bacloud23 👋🏻 
I could work on adding Bulgarian (bg locale) translations for both front/back. Let me know if you want me to give it a go 😃

**Comment by bacloud23** [comment]
yes of course ! you are welcome. I'm not assigning this to anyone as it stays open. After a successful PR I merge.

**Comment by bacloud23** [comment]
Hi @marinoffDev & @danieled-it 
Sadly the community around Classified-ads does not worth it. Too much traffic, clones and no contribution.
Traffic is to be expected on such solution to grab for free, but for all this time with no contributions this is actually a shame !
I'm closing its source. My effort went to vein but I learned something !

Closing the source today later, if you want to contribute tell me how do you want to contribute, and I will invite you to the private repo.
